// Copyright 2026 Antifraud Services Inc. under the Apache License, Version 2.0.

/**
 * Node runtime re-export of canonical consent claim helpers.
 */
export {
  addActorIdentifierList,
  addActorRoleList,
  addActors,
  addCategories,
  addCategoryList,
  addClaimValues,
  addPurposeList,
  addPurposes,
  addRoles,
  addSections,
  getActorIdentifierList,
  getActorRoleList,
  getActors,
  getCategories,
  getCategoryList,
  getClaimValues,
  getConsentDate,
  getConsentIdentifier,
  getConsentPeriodEnd,
  getConsentPeriodStart,
  getPurposeList,
  getPurposes,
  getRoles,
  getSections,
  setActorIdentifierList,
  setActorRoleList,
  setActors,
  setCategories,
  setCategoryList,
  setClaimValues,
  setConsentDate,
  setConsentIdentifier,
  setConsentPeriodEnd,
  setConsentPeriodStart,
  setPurposeList,
  setPurposes,
  setRoles,
  setSections,
  type ConsentInteroperableClaims,
} from 'gdc-sdk-core-ts';
